=== sosy-lab/benchexec/benchmark-1.9.dtd
<!ELEMENT benchmark ((rundefinition | option | propertyfile | tasks | requiredfiles | resultfiles | require )*, columns?)>
<!ELEMENT rundefinition (tasks | option | propertyfile | requiredfiles)*>

<!ELEMENT tasks (include | includesfile | exclude | excludesfile | append | withoutfile | option | propertyfile | requiredfiles)*>
<!ELEMENT include (#PCDATA)>
<!ELEMENT includesfile (#PCDATA)>
<!ELEMENT exclude (#PCDATA)>
<!ELEMENT excludesfile (#PCDATA)>
<!ELEMENT withoutfile (#PCDATA)>
<!ELEMENT append (#PCDATA)>

<!ELEMENT requiredfiles (#PCDATA)>
<!ELEMENT resultfiles (#PCDATA)>
<!ELEMENT require (#PCDATA)>

<!ELEMENT option (#PCDATA)>
<!ELEMENT propertyfile (#PCDATA)>
<!ELEMENT columns (column*)>
<!ELEMENT column (#PCDATA)>

<!ATTLIST rundefinition name CDATA #IMPLIED>

<!ATTLIST benchmark tool CDATA #REQUIRED>
<!ATTLIST benchmark memlimit CDATA #IMPLIED>
<!ATTLIST benchmark timelimit CDATA #IMPLIED>
<!ATTLIST benchmark hardtimelimit CDATA #IMPLIED>
<!ATTLIST benchmark cpuCores CDATA #IMPLIED>
<!ATTLIST benchmark threads CDATA #IMPLIED>

<!ATTLIST tasks name CDATA #IMPLIED>

<!ATTLIST require cpuModel CDATA #IMPLIED>
<!ATTLIST require cpuCores CDATA "1">
<!ATTLIST require memory   CDATA "1">

<!ATTLIST option name CDATA #REQUIRED>
<!ATTLIST column title CDATA #IMPLIED
                 numberOfDigits CDATA #IMPLIED>

=== sosy-lab/benchexec/doc/benchmark-example-rand.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark PUBLIC "+//IDN sosy-lab.org//DTD BenchExec benchmark 1.9//EN" "http://www.sosy-lab.org/benchexec/benchmark-1.9.dtd">
<!-- Example file for benchmark definition for BenchExec
     with dummy tool "rand" that simply returns random answers.
     No resource limits are specified. -->
<benchmark tool="rand">

  <!-- <rundefinition> defines a tool configuration to benchmark
       (tool rand does not need any arguments and has only one configuration). -->
  <rundefinition/>

  <!-- <tasks> defines a set of tasks:
       we define three sets of some arbitrary example files here. -->
  <tasks name="DTD files">
    <include>*.dtd</include>
  </tasks>

  <tasks name="Markdown files">
    <include>*.md</include>
  </tasks>

  <tasks name="XML files">
    <include>*.xml</include>
  </tasks>

  <!-- <tasks> with <withoutfile> allows to define tasks without input files,
       if the tool supports this. -->
  <tasks name="Dummy tasks">
    <withoutfile>dummy task 1</withoutfile>
    <withoutfile>dummy task 2</withoutfile>
    <withoutfile>dummy task 3</withoutfile>
  </tasks>
</benchmark>
